'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.perceptible.net/Oxygen/Settings/2006-04-18"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://schemas.perceptible.net/Oxygen/Settings/2006-04-18", IsNullable:=false)>  _
Partial Public Class Settings
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private entityGenerationIsEnabledField As Boolean
    
    Private entityGenerationDefaultTargetProjectNameField As String
    
    Private entityGenerationDefaultTargetSubFolderField As String
    
    Private entityGenerationDefaultTargetNamespaceField As String
    
    Private entityGenerationDefaultTargetLanguageField As String
    
    Private dalcGenerationIsEnabledField As Boolean
    
    Private dalcGenerationDefaultTargetProjectNameField As String
    
    Private dalcGenerationDefaultTargetSubFolderField As String
    
    Private dalcGenerationDefaultTargetNamespaceField As String
    
    Private dalcGenerationDefaultTargetLanguageField As String
    
    Private dalcGenerationDefaultInstanceNameField As String
    
    Private storedProceduresGenerationIsEnabledField As Boolean
    
    Private storedProceduresGenerationDefaultTargetProjectNameField As String
    
    Private storedProceduresGenerationDefaultTargetSubFolderField As String
    
    Private storedProceduresGenerationDefaultConnectionStringField As String
    
    Private storedProceduresGenerationDefaultRunScriptField As Boolean
    
    Private storedProceduresGenerationDefaultDatabaseNameField As String
    
    Private storedProceduresGenerationDefaultGranteesField() As String
    
    Private storedProceduresGenerationPrefixField As String
    
    Private itemNotFoundErrorNumberField As Integer
    
    Private itemCardinalityErrorNumberField As Integer
    
    Private itemConcurrencyErrorNumberField As Integer
    
    Private cachingDefaultInstanceNameField As String
    
    '''<remarks/>
    Public Property EntityGenerationIsEnabled() As Boolean
        Get
            Return Me.entityGenerationIsEnabledField
        End Get
        Set
            Me.entityGenerationIsEnabledField = value
            Me.RaisePropertyChanged("EntityGenerationIsEnabled")
        End Set
    End Property
    
    '''<remarks/>
    Public Property EntityGenerationDefaultTargetProjectName() As String
        Get
            Return Me.entityGenerationDefaultTargetProjectNameField
        End Get
        Set
            Me.entityGenerationDefaultTargetProjectNameField = value
            Me.RaisePropertyChanged("EntityGenerationDefaultTargetProjectName")
        End Set
    End Property
    
    '''<remarks/>
    Public Property EntityGenerationDefaultTargetSubFolder() As String
        Get
            Return Me.entityGenerationDefaultTargetSubFolderField
        End Get
        Set
            Me.entityGenerationDefaultTargetSubFolderField = value
            Me.RaisePropertyChanged("EntityGenerationDefaultTargetSubFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property EntityGenerationDefaultTargetNamespace() As String
        Get
            Return Me.entityGenerationDefaultTargetNamespaceField
        End Get
        Set
            Me.entityGenerationDefaultTargetNamespaceField = value
            Me.RaisePropertyChanged("EntityGenerationDefaultTargetNamespace")
        End Set
    End Property
    
    '''<remarks/>
    Public Property EntityGenerationDefaultTargetLanguage() As String
        Get
            Return Me.entityGenerationDefaultTargetLanguageField
        End Get
        Set
            Me.entityGenerationDefaultTargetLanguageField = value
            Me.RaisePropertyChanged("EntityGenerationDefaultTargetLanguage")
        End Set
    End Property
    
    '''<remarks/>
    Public Property DalcGenerationIsEnabled() As Boolean
        Get
            Return Me.dalcGenerationIsEnabledField
        End Get
        Set
            Me.dalcGenerationIsEnabledField = value
            Me.RaisePropertyChanged("DalcGenerationIsEnabled")
        End Set
    End Property
    
    '''<remarks/>
    Public Property DalcGenerationDefaultTargetProjectName() As String
        Get
            Return Me.dalcGenerationDefaultTargetProjectNameField
        End Get
        Set
            Me.dalcGenerationDefaultTargetProjectNameField = value
            Me.RaisePropertyChanged("DalcGenerationDefaultTargetProjectName")
        End Set
    End Property
    
    '''<remarks/>
    Public Property DalcGenerationDefaultTargetSubFolder() As String
        Get
            Return Me.dalcGenerationDefaultTargetSubFolderField
        End Get
        Set
            Me.dalcGenerationDefaultTargetSubFolderField = value
            Me.RaisePropertyChanged("DalcGenerationDefaultTargetSubFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property DalcGenerationDefaultTargetNamespace() As String
        Get
            Return Me.dalcGenerationDefaultTargetNamespaceField
        End Get
        Set
            Me.dalcGenerationDefaultTargetNamespaceField = value
            Me.RaisePropertyChanged("DalcGenerationDefaultTargetNamespace")
        End Set
    End Property
    
    '''<remarks/>
    Public Property DalcGenerationDefaultTargetLanguage() As String
        Get
            Return Me.dalcGenerationDefaultTargetLanguageField
        End Get
        Set
            Me.dalcGenerationDefaultTargetLanguageField = value
            Me.RaisePropertyChanged("DalcGenerationDefaultTargetLanguage")
        End Set
    End Property
    
    '''<remarks/>
    Public Property DalcGenerationDefaultInstanceName() As String
        Get
            Return Me.dalcGenerationDefaultInstanceNameField
        End Get
        Set
            Me.dalcGenerationDefaultInstanceNameField = value
            Me.RaisePropertyChanged("DalcGenerationDefaultInstanceName")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationIsEnabled() As Boolean
        Get
            Return Me.storedProceduresGenerationIsEnabledField
        End Get
        Set
            Me.storedProceduresGenerationIsEnabledField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationIsEnabled")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationDefaultTargetProjectName() As String
        Get
            Return Me.storedProceduresGenerationDefaultTargetProjectNameField
        End Get
        Set
            Me.storedProceduresGenerationDefaultTargetProjectNameField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationDefaultTargetProjectName")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationDefaultTargetSubFolder() As String
        Get
            Return Me.storedProceduresGenerationDefaultTargetSubFolderField
        End Get
        Set
            Me.storedProceduresGenerationDefaultTargetSubFolderField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationDefaultTargetSubFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationDefaultConnectionString() As String
        Get
            Return Me.storedProceduresGenerationDefaultConnectionStringField
        End Get
        Set
            Me.storedProceduresGenerationDefaultConnectionStringField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationDefaultConnectionString")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationDefaultRunScript() As Boolean
        Get
            Return Me.storedProceduresGenerationDefaultRunScriptField
        End Get
        Set
            Me.storedProceduresGenerationDefaultRunScriptField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationDefaultRunScript")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationDefaultDatabaseName() As String
        Get
            Return Me.storedProceduresGenerationDefaultDatabaseNameField
        End Get
        Set
            Me.storedProceduresGenerationDefaultDatabaseNameField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationDefaultDatabaseName")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Grantee", IsNullable:=false)>  _
    Public Property StoredProceduresGenerationDefaultGrantees() As String()
        Get
            Return Me.storedProceduresGenerationDefaultGranteesField
        End Get
        Set
            Me.storedProceduresGenerationDefaultGranteesField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationDefaultGrantees")
        End Set
    End Property
    
    '''<remarks/>
    Public Property StoredProceduresGenerationPrefix() As String
        Get
            Return Me.storedProceduresGenerationPrefixField
        End Get
        Set
            Me.storedProceduresGenerationPrefixField = value
            Me.RaisePropertyChanged("StoredProceduresGenerationPrefix")
        End Set
    End Property
    
    '''<remarks/>
    Public Property ItemNotFoundErrorNumber() As Integer
        Get
            Return Me.itemNotFoundErrorNumberField
        End Get
        Set
            Me.itemNotFoundErrorNumberField = value
            Me.RaisePropertyChanged("ItemNotFoundErrorNumber")
        End Set
    End Property
    
    '''<remarks/>
    Public Property ItemCardinalityErrorNumber() As Integer
        Get
            Return Me.itemCardinalityErrorNumberField
        End Get
        Set
            Me.itemCardinalityErrorNumberField = value
            Me.RaisePropertyChanged("ItemCardinalityErrorNumber")
        End Set
    End Property
    
    '''<remarks/>
    Public Property ItemConcurrencyErrorNumber() As Integer
        Get
            Return Me.itemConcurrencyErrorNumberField
        End Get
        Set
            Me.itemConcurrencyErrorNumberField = value
            Me.RaisePropertyChanged("ItemConcurrencyErrorNumber")
        End Set
    End Property
    
    '''<remarks/>
    Public Property CachingDefaultInstanceName() As String
        Get
            Return Me.cachingDefaultInstanceNameField
        End Get
        Set
            Me.cachingDefaultInstanceNameField = value
            Me.RaisePropertyChanged("CachingDefaultInstanceName")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class
